package com.booking.BookingApp.models.enums;

public enum NotificationTypeEnum {
    MESSAGE,RESERVATION_CREATED,RESERVATION_CANCELLED,RESERVATION_APPROVED,RESERVATION_REJECTED,OWNER_RATING,ACCOMMODATION_RATING
}
